version: '3'

services:
  track_manager:
    build:
      context: ./src/downloader
    volumes:
      - .:/workspace
      - ./.aws:/root/.aws:ro

    command: python3 /workspace/src/downloader/track_searcher.py

  test_track_manager:
    build:
      context: ./src/downloader
    volumes:
      - .:/workspace
    environment:
      - PYTHONPATH=/workspace
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
    command: python3 -m pytest /workspace/src/downloader/test_track_searcher.py -v

  preprocessor:
    build:
      context: ./src/preprocessor
    volumes:
      - .:/workspace
      - ./.aws:/root/.aws:ro
    command: python3 /workspace/src/preprocessor/preprocess.py

  trainer:
    build:
      context: ./src/trainer
    volumes:
      - .:/workspace
    command: python3 train.py processed/processed_tracks.csv --output-dir models

  generator:
    build:
      context: ./src/generator
    volumes:
      - ./src/generator:/workspace
    command: python3 generate.py models/model_final.pth input.wav --output-dir generated 