version: '3'

services:
  downloader:
    build:
      context: ./src/downloader
    volumes:
      - .:/workspace
    command: python3 soundcloud_downloader.py track_pairs.csv --output-dir downloads

  preprocessor:
    build:
      context: ./src/preprocessor
    volumes:
      - .:/workspace
    command: python3 audio_preprocessor.py downloads/downloaded_tracks.csv --output-dir processed

  trainer:
    build:
      context: ./src/trainer
    volumes:
      - .:/workspace
    command: python3 train.py processed/processed_tracks.csv --output-dir models

  generator:
    build:
      context: ./src/generator
    volumes:
      - ./src/generator:/workspace
    command: python3 generate.py models/model_final.pth input.wav --output-dir generated 