version: '3'

services:
  track_searcher:
    build:
      context: ./src/downloader
    volumes:
      - .:/workspace
    environment:
      - SEARCH_QUERY=anime lofi remix
      - MAX_TRACKS=5
    command: python3 /workspace/src/downloader/track_searcher.py

  track_downloader:
    build:
      context: ./src/downloader
    volumes:
      - .:/workspace
    environment:
      - S3_BUCKET=remixxx-resources
      - S3_PREFIX=raw_data
      - INPUT_CSV=track_pairs.csv
      - OUTPUT_DIR=downloads
    depends_on:
      - track_searcher
    command: python3 /workspace/src/downloader/track_downloader.py

  preprocessor:
    build:
      context: ./src/preprocessor
    volumes:
      - .:/workspace
    command: python3 audio_preprocessor.py downloads/downloaded_tracks.csv --output-dir processed

  trainer:
    build:
      context: ./src/trainer
    volumes:
      - .:/workspace
    command: python3 train.py processed/processed_tracks.csv --output-dir models

  generator:
    build:
      context: ./src/generator
    volumes:
      - ./src/generator:/workspace
    command: python3 generate.py models/model_final.pth input.wav --output-dir generated 